const mongoose = require('mongoose');

const ExamQuestionSchema = new mongoose.Schema({
  question: String,
  answer: String
}, { _id: false });

const LectureSchema = new mongoose.Schema({
  title: String,
  fileUrl: String, // Path/URL to the media file
  transcript: String,
  summary: mongoose.Schema.Types.Mixed, // The JSON object generated by Groq
  wordCount: Number,
  createdAt: { type: String, default: () => new Date().toISOString() }
}, { _id: false });

const NotificationSchema = new mongoose.Schema({
  lectureTitle: String,
  createdAt: String,
  readBy: [String]
}, { _id: false });

const SectionSchema = new mongoose.Schema({
  name: { type: String, required: true, trim: true },
  faculty: { type: String, required: true },
  students: [String],
  examQuestions: [ExamQuestionSchema],
  lectures: [LectureSchema],
  notifications: [NotificationSchema],
  createdAt: { type: String, default: () => new Date().toISOString() }
});

module.exports = mongoose.model('Section', SectionSchema);
